# Generated by Django 4.2 on 2023-05-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco'),
        ),
    ]
