# Generated by Django 4.2 on 2023-05-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_p', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
    ]
