# Generated by Django 4.2 on 2023-05-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='valor_g',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor G'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='valor_m',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor M'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='valor_p',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor P'),
        ),
    ]
