# Generated by Django 4.2 on 2023-05-10 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_pizza_imagem_alter_pizza_valor_g_alter_pizza_valor_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('fornecedores', models.ManyToManyField(blank=True, related_name='produtos', through='cadastros.Fornecimento', to='cadastros.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='fornecimento',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto'),
        ),
    ]
