# Generated by Django 4.2 on 2023-05-12 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_fornecimento_produto_fornecimento_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cadastros.login')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cadastros.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(max_length=11)),
                ('tipo_item', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField(max_length=11)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItensPedido', to='cadastros.pedido')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItensPedido', to='cadastros.pizza')),
            ],
        ),
    ]
